version: '3'
services:

  # Express Server
  express-server:
    container_name: express-server
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run watch-debug'
    ports: 
      - '3001:3001'
      - '9229:9229'
    volumes:
      - ./:/backendapp
      - '/backendapp/node_modules'
    links:
      - mysql-server
    depends_on:
      - mysql-server
      - redis-server

  # Redis
  redis-server:
    image: redis:4.0
    container_name: redis-server
    ports:
      - 6379:6379

  # Database
  mysql-server:
    image: mysql:5.7.21
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker_mysql_Server
      MYSQL_DATABASE: docker_mysql_Server
    ports:
      - 3306:3306
    volumes:
      - './.data/mysql:/var/lib/mysql'
      - './devops/server-configs/mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf'
    depends_on:
      - redis-server